/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutComponent: typeof import('./src/components/about/AboutComponent.vue')['default']
    ArticleComponent: typeof import('./src/components/blog/ArticleComponent.vue')['default']
    AuthorComponent: typeof import('./src/components/blog/AuthorComponent.vue')['default']
    BlogComponent: typeof import('./src/components/blog/BlogComponent.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FooterComponent: typeof import('./src/components/home/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/home/HeaderComponent.vue')['default']
    Main: typeof import('./src/components/home/Main.vue')['default']
    MainComponent: typeof import('./src/components/home/MainComponent.vue')['default']
    RecentArticleComponent: typeof import('./src/components/blog/RecentArticleComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./src/components/search/SearchComponent.vue')['default']
  }
}
